[package]
name = "mayo-hal"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["NaLaDcP"]
description = "A minimal no-std GPIO HAL for embedded systems"
keywords = ["embedded", "gpio", "no-std", "hal"]
categories = ["embedded", "no-std", "no-std::no-alloc"]
